version: '3'

networks:
  roachnet:

volumes:
  data-volume1:
  data-volume2:
  data-volume3:

services:

  roach1:
    hostname: roach1
    container_name: roach1
    image: cockroachdb/cockroach:v19.2.6
    networks:
      - roachnet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - data-volume1:/cockroach/cockroach-data
    command: start --insecure --join=roach1,roach2,roach3 --locality=region=us-east

  roach2:
    hostname: roach2
    container_name: roach2
    image: cockroachdb/cockroach:v19.2.6
    networks:
      - roachnet
    volumes:
      - data-volume2:/cockroach/cockroach-data
    depends_on:
      - roach1
    command: start --insecure --join=roach1,roach2,roach3 --locality=region=us-midwest

  roach3:
    hostname: roach3
    container_name: roach3
    image: cockroachdb/cockroach:v19.2.6
    networks:
      - roachnet
    volumes:
      - data-volume3:/cockroach/cockroach-data
    depends_on:
      - roach1
    command: start --insecure --join=roach1,roach2,roach3 --locality=region=us-west
